export const WECHAT_API_TOKEN = "WECHAT_API_ACCESS_TOKEN";
export const WECHAT_USER_TOKEN = "WECHAT_USER_ACCESS_TOKEN";
export const WECHAT_REFRESH_TOKEN = "WECHAT_REFRESH_ACCESS_TOKEN";
export const WECHAT_JS_API_TICKET = "WECHAT_JS_API_TICKET";
